sky:
  minio:
    endpoint: http://192.168.76.129:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: test-bucket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

